language: node_js
node_js:
  - "10"
branches:
  only:
    - master

jobs:
  include:
    stage: test
    before_script:
      - npm install
    script: npm run build


  stage: deploy
    before_script:
      - npm install
    script: npm run build
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep_history: true
    on:
      branch: gh_pages
